"""add language field to user

Revision ID: 6150ce402cf2
Revises: add_bought_to_shopping_items
Create Date: 2025-06-06 16:32:48.941787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6150ce402cf2'
down_revision: Union[str, None] = 'add_bought_to_shopping_items'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 